# -*- coding: utf-8 -*-
"""01_reference_sequence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O46yfcMDQc11P1VfYI7f6LpmbPNUjMnU
"""

!pip install biopython pandas numpy matplotlib

from Bio import SeqIO

record = SeqIO.read("/NC_000913.3_reference.fasta", "fasta")

print(record.id)
print(record.description)
print(len(record.seq))
print(record.seq[:100])

genome = str(record.seq).upper()

a = genome.count("A")
t = genome.count("T")
g = genome.count("G")
c = genome.count("C")
n = genome.count("N")

gc = ((g + c) / len(genome)) * 100

print("Genome length:", len(genome))
print("A:", a)
print("T:", t)
print("G:", g)
print("C:", c)
print("N:", n)
print("GC content:", round(gc, 2), "%")

print("Total bases counted:", a + t + g + c + n)

allowed = {"A", "T", "G", "C", "N"}

extra = set(genome) - allowed

print("Unexpected characters:", extra)

from Bio.Seq import Seq

start = 1694260
end = 1696071

uidA_region = genome[start - 1:end]

print("Region length:", len(uidA_region))

uidA = str(Seq(uidA_region).reverse_complement())

print("uidA length:", len(uidA))
print("First 60 bases:")
print(uidA[:60])

print("\nLast 60 bases:")
print(uidA[-60:])

uidA_gc = ((uidA.count("G") + uidA.count("C")) / len(uidA)) * 100

print("Length:", len(uidA))
print("GC content:", round(uidA_gc, 2), "%")
print("N bases:", uidA.count("N"))

protein = Seq(uidA).translate()

print("Protein length:", len(protein))
print("First 30 amino acids:")
print(protein[:30])
print("Stop codons:", protein.count("*"))
print("Last 10 amino acids:")
print(protein[-10:])

print("DNA length:", len(uidA))
print("Number of codons:", len(uidA) // 3)
print("Translated length:", len(protein))
print("Stop codons:", protein.count("*"))
print("Ends with stop:", protein.endswith("*"))

from Bio.SeqRecord import SeqRecord

uidA_record = SeqRecord(
    Seq(uidA),
    id="uidA",
    description="E. coli K-12 MG1655 uidA gene"
)

SeqIO.write(uidA_record, "uidA_reference.fasta", "fasta")

print("uidA_reference.fasta saved")

import os

print("Current folder:", os.getcwd())
print(os.listdir())

from google.colab import files

files.download("uidA_reference.fasta")

forward_primer = "TTGCAACTGGACAAGGCACTA"
reverse_primer = "GTTCTTTCGGCTTGTTGCCC"

print("Forward primer:", forward_primer)
print("Reverse primer:", reverse_primer)
print("Forward length:", len(forward_primer))
print("Reverse length:", len(reverse_primer))

forward_gc = ((forward_primer.count("G") + forward_primer.count("C")) / len(forward_primer)) * 100
reverse_gc = ((reverse_primer.count("G") + reverse_primer.count("C")) / len(reverse_primer)) * 100

print("Forward GC:", round(forward_gc, 2), "%")
print("Reverse GC:", round(reverse_gc, 2), "%")

reverse_binding = str(Seq(reverse_primer).reverse_complement())

forward_pos = uidA.find(forward_primer)
reverse_pos = uidA.find(reverse_binding)

print("Forward primer starts at:", forward_pos + 1)
print("Reverse binding site starts at:", reverse_pos + 1)
print("Reverse binding sequence:", reverse_binding)

amplicon = uidA[forward_pos:reverse_pos + len(reverse_binding)]

print("Amplicon length:", len(amplicon))
print("First 30 bases:", amplicon[:30])
print("Last 30 bases:", amplicon[-30:])

amplicon_record = SeqRecord(
    Seq(amplicon),
    id="uidA_amplicon",
    description="450 bp predicted PCR product"
)

SeqIO.write(amplicon_record, "uidA_amplicon.fasta", "fasta")

print("uidA_amplicon.fasta saved")

from google.colab import files

files.download("uidA_amplicon.fasta")

amplicon_gc = ((amplicon.count("G") + amplicon.count("C")) / len(amplicon)) * 100

print("Amplicon length:", len(amplicon))
print("GC content:", round(amplicon_gc, 2), "%")
print("A:", amplicon.count("A"))
print("T:", amplicon.count("T"))
print("G:", amplicon.count("G"))
print("C:", amplicon.count("C"))
print("N:", amplicon.count("N"))

print("Starts with forward primer:", amplicon.startswith(forward_primer))
print("Ends with reverse primer binding site:", amplicon.endswith(reverse_binding))

sanger_read = amplicon[:400]

print("Read length:", len(sanger_read))
print("First 30 bases:", sanger_read[:30])
print("Last 30 bases:", sanger_read[-30:])

quality = []

for i in range(len(sanger_read)):
    if i < 20:
        quality.append(20)
    elif i > 370:
        quality.append(22)
    else:
        quality.append(35)

print("Number of quality scores:", len(quality))
print("First 30 scores:", quality[:30])
print("Last 30 scores:", quality[-30:])

average_quality = sum(quality) / len(quality)

q30_bases = 0

for score in quality:
    if score >= 30:
        q30_bases += 1

q30_percent = (q30_bases / len(quality)) * 100

print("Average quality:", round(average_quality, 2))
print("Bases with Q30 or higher:", q30_bases)
print("Q30 percentage:", round(q30_percent, 2), "%")

trimmed_read = sanger_read[20:371]
trimmed_quality = quality[20:371]

print("Original read length:", len(sanger_read))
print("Trimmed read length:", len(trimmed_read))
print("Bases removed:", len(sanger_read) - len(trimmed_read))
print("Lowest quality after trimming:", min(trimmed_quality))

reference_region = amplicon[20:371]

matches = 0

for i in range(len(trimmed_read)):
    if trimmed_read[i] == reference_region[i]:
        matches += 1

identity = (matches / len(trimmed_read)) * 100

print("Bases compared:", len(trimmed_read))
print("Matching bases:", matches)
print("Sequence identity:", round(identity, 2), "%")

mismatches = []

for i in range(len(trimmed_read)):
    if trimmed_read[i] != reference_region[i]:
        mismatches.append(i + 1)

print("Number of mismatches:", len(mismatches))
print("Mismatch positions:", mismatches)

import matplotlib.pyplot as plt

positions = range(1, len(quality) + 1)

plt.plot(positions, quality)

plt.xlabel("Base position")
plt.ylabel("Quality score")
plt.title("Simulated Sanger read quality")

plt.show()

plt.figure(figsize=(10, 5))

plt.plot(positions, quality)

plt.xlabel("Base position")
plt.ylabel("Phred quality score")
plt.title("Simulated Sanger Read Quality Profile")

plt.axhline(y=30, linestyle="--", label="Q30 threshold")

plt.legend()
plt.tight_layout()

plt.savefig("sanger_quality_profile.png", dpi=300)
plt.show()

print("sanger_quality_profile.png saved")